LASTKAJEN_GEOPACKAGES_TO_MERGE: C:\Users\SEJC94056\Documents\General Layers\Lastkajen_Layers
EMME_GEOPACKAGE_TO_MERGE: C:\Users\SEJC94056\Documents\General Layers\Emme_Processed_Layers
LASTKAJEN_LAYERS_NAME: TRAFIK_DK_O_105_Trafik
MOBILE_POLIGONS: C:\Users\SEJC94056\Documents\General Layers\Telia_Layers